# -*- coding: utf-8 -*-
"""TrainLisensePlate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XaW9fh8xsbRZklmArDO2joG7Y5wABFJk
"""

!pip install git+https://github.com/ultralytics/ultralytics.git
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="EaizOCPRYmGzn34wUlz8")
project = rf.workspace("dunghaquang").project("license-plate-detection-opksu")
version = project.version(2)
dataset = version.download("yolov8")

from ultralytics import YOLO
model = YOLO('yolov8n.pt')

# Huấn luyện mô hình
model.train(
    data='/content/License-plate-detection-2/data.yaml',  # Đường dẫn đến file data.yaml
    epochs=100,           # Số lượng epochs
    imgsz=640,           # Kích thước ảnh
    batch=16,            # Kích thước batch
    workers=2            # Số lượng workers
)

# Lưu mô hình vào thư mục Google Drive
model.save("/content/drive/MyDrive/NGANGIANGINTERNSHIP/Job74/License-plate-detection.pt")

# Dự đoán với mô hình đã huấn luyện
results = model("/content/drive/MyDrive/NGANGIANGINTERNSHIP/Job74/GreenParking/0000_06886_b.jpg")
print(results[0])
# Hiển thị kết quả
results[0].plot()  # Hiển thị ảnh với các bounding box và nhãn